docs: add log applicatifs
SocialGouv/support pull request #516
Opened 2023-12-18 14:40 UTC by revolunet

2023-12-27 20:43 UTC, achauve requested changes

2023-12-27 20:43 UTC, achauve commented on docs/standards/kubernetes.md
> +| Obligation | Les métriques applicatives sont exposés sur un endpoint `/metrics`      |
Pas du tout obligatoire à mon sens, c'est plus facile de passer par sentry

2023-12-27 21:16 UTC, revolunet commented on docs/standards/kubernetes.md
> +| Obligation | Les métriques applicatives sont exposés sur un endpoint `/metrics`      |
oui, a corriger :)

2024-01-08 13:48 UTC, matmut7 approved these changes

2024-01-08 13:48 UTC, devthejo approved these changes

2024-01-08 14:01 UTC, merged